# Generated by Django 5.1.3 on 2025-01-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buidingFaciliSysApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='proof',
            field=models.FileField(null=True, upload_to='proofs/'),
        ),
    ]
