# Generated by Django 5.1.3 on 2025-01-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buidingFaciliSysApp', '0002_contractor_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='last_login',
        ),
    ]
