# Generated by Django 5.1.3 on 2025-01-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buidingFaciliSysApp', '0003_remove_contractor_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='proof',
            field=models.FileField(null=True, upload_to='proofs/'),
        ),
    ]
