# Generated by Django 5.1.3 on 2025-01-25 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buidingFaciliSysApp', '0005_remove_customer_request_confirm_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_feedback',
            name='worker_allocation',
        ),
        migrations.AddField(
            model_name='request_feedback',
            name='Customer_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buidingFaciliSysApp.customer_request'),
        ),
    ]
